version: "3.8"
services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: always
  redis:
    image: redis
    container_name: redis
    ports: 
      - "6379:6379"
    restart: always